server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.231.159:3306/practice
    username: hehanglin
    password: '@666Hehanglin'

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tRi3XCBJXipE3VjZRjC
    accessKeySecret: t7e0McAwkNBxdjUcssrlXAu0KL6XbG
    bucketName: practice-springboot-web


# spring ??????
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

